# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Dysfunctional Programming'
tagline:             'A Blog & Portfolio for Kevin Romano'
description:         'A simple blog and portfolio to help others learn what I have learned'
url:                 http://kevrom.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kevin Romano
  url:               https://twitter.com/kevrom
  email:             kevrom@gmail.com

# Custom vars
version:             1.0.0