# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Functionally Dysfunctional
email: kevrom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A portfolio and blog for Kevin Romano.  Musings and explanations and projects and fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kevrom.com" # the base hostname & protocol for your site
twitter_username: kevrom
github_username:  kevrom

# Build settings
markdown: kramdown
